// builds the kit yassin.app's room uses around the embedded desktop:
//   public/embed/room-theme.json  yassinOS's look, the span image and the screen layout
//   public/embed/room-span.webp   one wallpaper spanning the room's three screens
//
// node scripts/roomSpan.js                  theme and image
// node scripts/roomSpan.js --theme-only     just the theme
// node scripts/roomSpan.js --preview a.png  also a small preview with the bezels drawn in
//
// the image is drawn on a canvas in playwright's chromium
// (`yarn playwright install chromium` if it's missing)

const { existsSync, mkdirSync, readFileSync, writeFileSync } = require("fs");
const { dirname, join, resolve } = require("path");
const ts = require("typescript");

const ROOT = resolve(__dirname, "..");
const OUT_DIR = join(ROOT, "public/embed");
const IMAGE_FILE = "room-span.webp";
const THEME_FILE = "room-theme.json";
const MAX_IMAGE_BYTES = 400 * 1024;
const PX_PER_MM = 3;

// the room in millimetres, x right and y down from the top left corner
const ROOM_MM = { width: 976.4, height: 705.4 };
const SCREENS = {
  M1: {
    display: "main",
    content: "yassinOS",
    css: { width: 1600, height: 900 },
    rect: [0, 369.7, 596.7, 335.7],
  },
  M2: { display: "top", content: "widgets", rect: [0, 0, 596.7, 335.7] },
  M3: {
    display: "right",
    content: "terminal",
    orientation: "portrait",
    rect: [640.7, 56.35, 335.7, 596.7],
  },
};

// loads a module from the app's typescript sources, with paths from the repo
// root like tsconfig's baseUrl, so the theme values are the real ones
const STUBS = {
  "next/dynamic": { __esModule: true, default: () => () => null },
};
const loaded = new Map();

const loadSource = (request) => {
  if (STUBS[request]) return STUBS[request];

  const file = [".ts", ".tsx", "/index.ts"]
    .map((extension) => join(ROOT, `${request}${extension}`))
    .find((path) => existsSync(path));

  if (!file) return require(request);

  if (!loaded.has(file)) {
    const module = { exports: {} };
    const { outputText } = ts.transpileModule(readFileSync(file, "utf8"), {
      compilerOptions: {
        esModuleInterop: true,
        jsx: ts.JsxEmit.ReactJSX,
        module: ts.ModuleKind.CommonJS,
        target: ts.ScriptTarget.ES2022,
      },
      fileName: file,
    });

    loaded.set(file, module);
    new Function("exports", "require", "module", outputText)(
      module.exports,
      loadSource,
      module
    );
  }

  return loaded.get(file).exports;
};

const round = (value, digits = 6) => Number(value.toFixed(digits));

const hslToHex = (css) => {
  const [h, s, l] = css
    .match(/[\d.]+/g)
    .slice(0, 3)
    .map(Number);
  const saturation = s / 100;
  const lightness = l / 100;
  const chroma = saturation * Math.min(lightness, 1 - lightness);
  const channel = (n) => {
    const k = (n + h / 30) % 12;
    const value = lightness - chroma * Math.max(-1, Math.min(k - 3, 9 - k, 1));

    return Math.round(value * 255)
      .toString(16)
      .padStart(2, "0")
      .toUpperCase();
  };

  return `#${channel(0)}${channel(8)}${channel(4)}`;
};

const toRect = ([x, y, width, height]) => ({ x, y, width, height });

const buildTheme = () => {
  const { default: colors } = loadSource("styles/defaultTheme/colors");
  const { default: sizes } = loadSource("styles/defaultTheme/sizes");
  const { default: formats } = loadSource("styles/defaultTheme/formats");
  const { HOME, PACKAGE_DATA, TASKBAR_HEIGHT } = loadSource("utils/constants");
  const { config: terminal, PROMPT_CHARACTER } = loadSource(
    "components/apps/Terminal/config"
  );
  const {
    default: { Terminal },
  } = loadSource("contexts/process/directory");
  const imagePx = {
    width: Math.round(ROOM_MM.width * PX_PER_MM),
    height: Math.round(ROOM_MM.height * PX_PER_MM),
  };

  return {
    $comment:
      "generated by scripts/roomSpan.js from yassinOS's theme, don't edit by hand",
    name: PACKAGE_DATA.alias,
    version: 1,
    colors: {
      background: colors.background,
      text: colors.text,
      textBright: colors.fileEntry.text,
      textInactive: colors.titleBar.textInactive,
      textShadow: colors.fileEntry.textShadow.replace(/\s+/g, " ").trim(),
      accent: colors.highlight,
      accentHex: hslToHex(colors.highlight),
      accentDeep: colors.selectionHighlight,
      accentDeepHex: hslToHex(colors.selectionHighlight),
      selection: colors.selectionHighlightBackground,
      progress: colors.progress,
    },
    fonts: {
      ui: formats.systemFont,
      uiSize: sizes.fileEntry.fontSize,
      mono: terminal.fontFamily,
      monoSize: `${terminal.fontSize}px`,
      monoWeight: terminal.fontWeight,
    },
    radius: { menu: 0, taskbar: 0, window: 0 },
    taskbar: {
      height: TASKBAR_HEIGHT,
      background: colors.taskbar.background,
      blur: sizes.taskbar.blur,
      hover: colors.taskbar.hover,
      active: colors.taskbar.active,
      activeForeground: colors.taskbar.activeForeground,
      foreground: colors.taskbar.foreground,
      foregroundHover: colors.taskbar.foregroundHover,
      buttonColor: colors.taskbar.button.color,
      buttonWidth: sizes.taskbar.button.width,
      clockFontSize: sizes.clock.fontSize,
      entryFontSize: sizes.taskbar.entry.fontSize,
      entryIconSize: sizes.taskbar.entry.iconSize,
      entryMaxWidth: sizes.taskbar.entry.maxWidth,
      panelBlur: sizes.taskbar.panelBlur,
    },
    window: {
      background: colors.window.background,
      outline: `${sizes.window.outline} solid ${colors.window.outline}`,
      outlineInactive: `${sizes.window.outline} solid ${colors.window.outlineInactive}`,
      shadow: colors.window.shadow,
      shadowInactive: colors.window.shadowInactive,
      titleBar: {
        height: sizes.titleBar.height,
        background: colors.titleBar.background,
        backgroundHover: colors.titleBar.backgroundHover,
        backgroundInactive: colors.titleBar.backgroundInactive,
        text: colors.titleBar.text,
        textInactive: colors.titleBar.textInactive,
        fontSize: sizes.titleBar.fontSize,
        iconSize: sizes.titleBar.iconSize,
        buttonWidth: sizes.titleBar.buttonWidth,
        buttonInactive: colors.titleBar.buttonInactive,
        closeHover: colors.titleBar.closeHover,
      },
    },
    terminal: {
      background: Terminal.backgroundColor,
      backdropBlur: Terminal.backgroundBlur,
      foreground: terminal.theme.foreground,
      fontFamily: terminal.fontFamily,
      fontSize: terminal.fontSize,
      fontWeight: terminal.fontWeight,
      cursorStyle: terminal.cursorStyle,
      cursorBlink: terminal.cursorBlink,
      prompt: `${HOME}${PROMPT_CHARACTER}`,
      banner: [
        `${PACKAGE_DATA.alias} [Version ${PACKAGE_DATA.version}]`,
        `By ${PACKAGE_DATA.author.name}. ${PACKAGE_DATA.license} License.`,
      ],
    },
    span: {
      path: `/embed/${IMAGE_FILE}`,
      px: imagePx,
      mm: ROOM_MM,
      pxPerMm: PX_PER_MM,
    },
    screens: Object.fromEntries(
      Object.entries(SCREENS).map(([id, { rect, ...screen }]) => {
        const [x, y, width, height] = rect;

        return [
          id,
          {
            ...screen,
            mm: toRect(rect),
            norm: toRect([
              round(x / ROOM_MM.width),
              round(y / ROOM_MM.height),
              round(width / ROOM_MM.width),
              round(height / ROOM_MM.height),
            ]),
            px: toRect(rect.map((value) => round(value * PX_PER_MM, 2))),
          },
        ];
      })
    ),
    poster: {
      path: "/embed/poster-main.webp",
      screen: "M1",
      width: SCREENS.M1.css.width,
      height: SCREENS.M1.css.height,
    },
  };
};

// runs in the page: a twisting ribbon of fine lines in the accent blues. it
// enters the top screen from the left and pinches, crosses the bezel to the
// main screen wide open, pinches again on its right side and thins to a
// thread across the portrait screen's bottom corner, clear of the terminal
const drawRoom = ({ accent, accentDeep, pxPerMm, px, preview, screens }) => {
  const canvas = document.createElement("canvas");
  const ctx = canvas.getContext("2d");

  canvas.width = px.width;
  canvas.height = px.height;
  ctx.fillStyle = "#000";
  ctx.fillRect(0, 0, px.width, px.height);

  const smooth = (edge0, edge1, value) => {
    const t = Math.min(1, Math.max(0, (value - edge0) / (edge1 - edge0)));

    return t * t * (3 - 2 * t);
  };
  // catmull-rom through the ribbon's path, in mm (the first and last points
  // only steer the ends)
  const path = [
    [-220, 40],
    [-60, 92],
    [190, 172],
    [370, 300],
    [470, 440],
    [560, 540],
    [680, 600],
    [770, 710],
    [900, 880],
  ];
  const at = (t) => {
    const scaled = Math.min(0.9999, Math.max(0, t)) * (path.length - 3);
    const i = Math.floor(scaled) + 1;
    const u = scaled - (i - 1);
    const [p0, p1, p2, p3] = [path[i - 1], path[i], path[i + 1], path[i + 2]];

    return [0, 1].map(
      (axis) =>
        0.5 *
        (2 * p1[axis] +
          (p2[axis] - p0[axis]) * u +
          (2 * p0[axis] - 5 * p1[axis] + 4 * p2[axis] - p3[axis]) * u * u +
          (3 * p1[axis] - p0[axis] - 3 * p2[axis] + p3[axis]) * u * u * u)
    );
  };
  const STEPS = 900;
  const LINES = 34;
  const centre = Array.from({ length: STEPS + 1 }, (_, step) =>
    at(step / STEPS)
  );
  const normals = centre.map((point, step) => {
    const [ax, ay] = centre[Math.max(0, step - 1)];
    const [bx, by] = centre[Math.min(STEPS, step + 1)];
    const length = Math.hypot(bx - ax, by - ay) || 1;

    return [-(by - ay) / length, (bx - ax) / length];
  });
  // the ribbon pinches on the top screen, crosses to the main screen wide
  // open, pinches again and thins to a thread before the portrait screen
  const lineAt = (u, step) => {
    const t = step / STEPS;
    const envelope =
      t < 0.4
        ? 0.45 + 0.55 * smooth(0, 0.4, t)
        : 1 - 0.94 * smooth(0.4, 0.9, t);
    const halfWidth = 78 * envelope;
    const twist = 0.08 + 7.5 * t;
    const offset =
      halfWidth * (u * Math.cos(twist) + 0.14 * Math.sin(twist + u * 1.7));
    const [x, y] = centre[step];
    const [nx, ny] = normals[step];

    return [x + nx * offset, y + ny * offset];
  };
  const [startX, startY] = at(0);
  const [endX, endY] = at(0.97);
  const gradient = (alpha) => {
    const fill = ctx.createLinearGradient(startX, startY, endX, endY);

    fill.addColorStop(0, `hsla(${accentDeep} / ${alpha * 0.35})`);
    fill.addColorStop(0.2, `hsla(${accentDeep} / ${alpha * 0.85})`);
    fill.addColorStop(0.45, `hsla(${accent} / ${alpha})`);
    fill.addColorStop(0.75, `hsla(${accent} / ${alpha * 0.7})`);
    fill.addColorStop(1, `hsla(${accent} / 0)`);

    return fill;
  };
  const strokeLines = (target, width, alpha) => {
    target.lineCap = "round";
    target.lineJoin = "round";
    target.lineWidth = width;

    for (let line = 0; line < LINES; line += 1) {
      const u = -1 + (2 * line) / (LINES - 1);

      target.strokeStyle = gradient(alpha * (1 - 0.65 * Math.abs(u)));
      target.beginPath();

      for (let step = 0; step <= STEPS; step += 1) {
        const [x, y] = lineAt(u, step);

        if (step === 0) target.moveTo(x, y);
        else target.lineTo(x, y);
      }

      target.stroke();
    }
  };

  ctx.setTransform(pxPerMm, 0, 0, pxPerMm, 0, 0);

  // a faint deep blue haze at the pinch and where the ribbon crosses the
  // bezel, kept tight so most of the room stays true black
  ctx.globalCompositeOperation = "lighter";
  [
    [215, 185, 110, 0.12],
    [420, 360, 150, 0.08],
  ].forEach(([x, y, radius, alpha]) => {
    const haze = ctx.createRadialGradient(x, y, 0, x, y, radius);

    haze.addColorStop(0, `hsla(${accentDeep} / ${alpha})`);
    haze.addColorStop(0.55, `hsla(${accentDeep} / ${alpha * 0.35})`);
    haze.addColorStop(1, `hsla(${accentDeep} / 0)`);
    ctx.fillStyle = haze;
    ctx.fillRect(x - radius, y - radius, radius * 2, radius * 2);
  });

  // glow: the lines drawn wide on their own layer, blurred and added on top
  const glow = document.createElement("canvas");
  const glowCtx = glow.getContext("2d");

  glow.width = px.width;
  glow.height = px.height;
  glowCtx.setTransform(pxPerMm, 0, 0, pxPerMm, 0, 0);
  strokeLines(glowCtx, 1.6, 0.2);
  ctx.setTransform(1, 0, 0, 1, 0, 0);
  ctx.filter = `blur(${Math.round(4 * pxPerMm)}px)`;
  ctx.drawImage(glow, 0, 0);
  ctx.filter = "none";
  ctx.setTransform(pxPerMm, 0, 0, pxPerMm, 0, 0);
  strokeLines(ctx, 0.36, 0.78);
  ctx.globalCompositeOperation = "source-over";
  ctx.setTransform(1, 0, 0, 1, 0, 0);

  // a little noise on anything lit, so the soft falloff doesn't band;
  // true black stays true black
  const image = ctx.getImageData(0, 0, px.width, px.height);
  const { data } = image;
  let seed = 7;

  for (let i = 0; i < data.length; i += 4) {
    if (data[i] + data[i + 1] + data[i + 2] > 6) {
      seed = (Math.imul(seed, 1103515245) + 12345) & 0x7fffffff;

      const noise = (seed / 0x7fffffff - 0.5) * 2.4;

      data[i] = Math.max(1, data[i] + noise);
      data[i + 1] = Math.max(1, data[i + 1] + noise);
      data[i + 2] = Math.max(1, data[i + 2] + noise);
    }
  }

  ctx.putImageData(image, 0, 0);

  const result = { image: canvas.toDataURL("image/webp", 0.86) };

  if (preview) {
    // the room as seen: bezels in dark grey, a third of the size
    const scale = 1 / 3;
    const room = document.createElement("canvas");
    const roomCtx = room.getContext("2d");

    room.width = Math.round(px.width * scale);
    room.height = Math.round(px.height * scale);
    roomCtx.fillStyle = "#1b1d21";
    roomCtx.fillRect(0, 0, room.width, room.height);
    Object.values(screens).forEach(({ rect: [x, y, width, height] }) => {
      const k = pxPerMm * scale;

      roomCtx.drawImage(
        canvas,
        x * pxPerMm,
        y * pxPerMm,
        width * pxPerMm,
        height * pxPerMm,
        x * k,
        y * k,
        width * k,
        height * k
      );
    });
    result.preview = room.toDataURL("image/png");
  }

  return result;
};

const writeDataUrl = (file, dataUrl) => {
  const bytes = Buffer.from(dataUrl.split(",")[1], "base64");

  mkdirSync(dirname(file), { recursive: true });
  writeFileSync(file, bytes);

  return bytes.length;
};

const main = async () => {
  const args = process.argv.slice(2);
  const previewIndex = args.indexOf("--preview");
  const preview = previewIndex === -1 ? "" : resolve(args[previewIndex + 1]);
  const theme = buildTheme();

  mkdirSync(OUT_DIR, { recursive: true });
  writeFileSync(
    join(OUT_DIR, THEME_FILE),
    `${JSON.stringify(theme, null, 2)}\n`
  );
  console.info(`wrote public/embed/${THEME_FILE}`);

  if (args.includes("--theme-only")) return;

  const { chromium } = require("playwright-core");
  const browser = await chromium.launch();

  try {
    const page = await browser.newPage();
    const hslParts = (css) =>
      css
        .match(/[\d.]+%?/g)
        .slice(0, 3)
        .join(" ");
    const result = await page.evaluate(drawRoom, {
      accent: hslParts(theme.colors.accent),
      accentDeep: hslParts(theme.colors.accentDeep),
      preview: Boolean(preview),
      px: theme.span.px,
      pxPerMm: PX_PER_MM,
      screens: SCREENS,
    });
    const size = writeDataUrl(join(OUT_DIR, IMAGE_FILE), result.image);

    console.info(
      `wrote public/embed/${IMAGE_FILE} (${theme.span.px.width} x ${theme.span.px.height}, ${Math.round(size / 1024)} KB)`
    );

    if (size > MAX_IMAGE_BYTES) {
      throw new Error(`${IMAGE_FILE} is over ${MAX_IMAGE_BYTES / 1024} KB`);
    }

    if (preview) {
      writeDataUrl(preview, result.preview);
      console.info(`wrote ${preview}`);
    }
  } finally {
    await browser.close();
  }
};

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
